name: senslerdeutsches-woerterbuch

services:
  # --- DEVCONTAINER ---
  workspace:
    profiles:
      - devcontainer
    build:
      context: .
      dockerfile: docker/workspace/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    networks:
      - sw-network

  # --- SHARED SERVICES ---
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - sw-network

  opensearch:
    build:
      context: .
      dockerfile: docker/opensearch/Dockerfile
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=false
      - plugins.security.ssl.http.enabled=false
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD}
    networks:
      - sw-network

  # --- PRODUCTION SERVICES ---
  traefik:
    profiles:
      - prod
    image: traefik:v3.6
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
      - "--accesslog=true"
    ports:
      - "80:80"
      - "8080:8080"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      sw-network:
        aliases:
          - frontend # This lets E2E hit Treafik using the service name
          - backend # This lets E2E hit Treafik using the service name

  backend:
    profiles:
      - prod
    build:
      context: .
      dockerfile: docker/admin-app/Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${BACKEND_DOMAIN}`) || Host(`backend`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
    environment:
      # Enable unbuffered output for better logging in Docker
      - PYTHONUNBUFFERED=1
      - POSTGRES_HOST=db
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - OPENSEARCH_HOST=${OPENSEARCH_HOST}
      - OPENSEARCH_ADMIN_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD}
    networks:
      - sw-network
    depends_on:
      - db

  frontend:
    profiles:
      - prod
    build:
      context: .
      dockerfile: docker/public-app/Dockerfile
      args:
        NG_ENV: ${NG_ENV}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${FRONTEND_DOMAIN}`) || Host(`frontend`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    networks:
      - sw-network

  # --- TEST SERVICES ---
  e2e:
    profiles:
      - test
    build:
      context: .
      dockerfile: docker/e2e/Dockerfile
    environment:
      - FRONTEND_DOMAIN=frontend
    volumes:
      - ./e2e/playwright-report:/app/playwright-report
      - ./e2e/test-results:/app/test-results
    networks:
      - sw-network

networks:
  sw-network:
    driver: bridge # ??
