services:
  admin-app:
    build:
      context: .
      dockerfile: docker/admin-app/Dockerfile
    networks:
      - sw-network

  proxy:
    build:
      context: .
      dockerfile: docker/proxy/Dockerfile
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "${PROXY_PORT}:80"
    volumes:
      - ./docker/proxy/logs/nginx:/var/log/nginx
    networks:
      - sw-network

networks:
  sw-network:
    driver: bridge