name: senslerdeutsches-woerterbuch

services:
  workspace:
    image: mcr.microsoft.com/devcontainers/python:3.12
    env_file: # Is this really needed here?
      - .env
    volumes: # Again, reall needed?
      - .:/workspace:cached
      
    # Map BOTH ports so you can see both apps
    ports:
      - "8000:8000" # Django
      - "4200:4200" # Angular
      
    # Keeps the container alive so you can open terminals inside it
    command: sleep infinity
    networks:
      - sw-network

  traefik:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - sw-network

  admin-app:
    build:
      context: .
      dockerfile: docker/admin-app/Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin-app.rule=Host(`admin-app.localhost`)"
      - "traefik.http.services.admin-app.loadbalancer.server.port=8000"
    env_file:
      - .env
    networks:
      - sw-network

  public-app:
    build:
      context: .
      dockerfile: docker/public-app/Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.public-app.rule=Host(`localhost`)"
      - "traefik.http.services.public-app.loadbalancer.server.port=80"
    networks:
      - sw-network

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - sw-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - sw-network

  opensearch:
    build:
      context: .
      dockerfile: docker/opensearch/Dockerfile
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=false
      - plugins.security.ssl.http.enabled=false
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.opensearch.rule=Host(`localhost`) && PathPrefix(`/opensearch`)"
      - "traefik.http.middlewares.opensearch-strip.stripprefix.prefixes=/opensearch"
      - "traefik.http.routers.opensearch.middlewares=opensearch-strip"
      - "traefik.http.services.opensearch.loadbalancer.server.port=9200"
    networks:
      - sw-network

  e2e:
    build:
      context: .
      dockerfile: docker/e2e/Dockerfile
    environment:
      - FRONTEND_URL=${PROXY_URL}
    volumes:
      - ./e2e/playwright-report:/app/playwright-report
      - ./e2e/test-results:/app/test-results
    networks:
      - sw-network

networks:
  sw-network:
    driver: bridge
