name: senslerdeutsches-woerterbuch

services:
  # --- SHARED SERVICES ---
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sw-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  opensearch:
    build:
      context: .
      dockerfile: docker/opensearch/Dockerfile
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=false
      - plugins.security.ssl.http.enabled=false
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD}
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - sw-network

  # --- PRODUCTION SERVICES ---
  traefik:
    image: traefik:v3.6
    command:
      - "--api.insecure=${TRAEFIK_DASHBOARD}"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--log.level=${TRAEFIK_LOG_LEVEL}"
      - "--accesslog=${TRAEFIK_ACCESS_LOG}"
    ports:
      - "80:80"
      - "8080:8080"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      sw-network:
        aliases:
          - frontend # This lets E2E hit Treafik using the service name
          - backend # This lets E2E hit Treafik using the service name

  backend:
    build:
      context: .
      dockerfile: docker/admin-app/Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${BACKEND_DOMAIN}`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
      # Routing for frontend
      - traefik.http.routers.backend_api.rule=Host(`${FRONTEND_DOMAIN}`) && PathPrefix(`/api`)
      - traefik.http.routers.backend_api.entrypoints=web
      - traefik.http.routers.backend_api.middlewares=strip-api
      - traefik.http.middlewares.strip-api.stripprefix.prefixes=/api
    environment:
      # Enable unbuffered output for better logging in Docker
      - PYTHONUNBUFFERED=1
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - OPENSEARCH_HOST=${OPENSEARCH_HOST}
      - OPENSEARCH_ADMIN_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD}
      - OPENSEARCH_INDEX_NAME=${OPENSEARCH_INDEX_NAME}
    networks:
      - sw-network
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: docker/public-app/Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${FRONTEND_DOMAIN}`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    networks:
      - sw-network

  # --- TEST SERVICES ---
  e2e:
    build:
      context: .
      dockerfile: docker/e2e/Dockerfile
    environment:
      - FRONTEND_DOMAIN=${FRONTEND_DOMAIN}
    volumes:
      - ./e2e/playwright-report:/app/playwright-report
      - ./e2e/test-results:/app/test-results
    networks:
      - sw-network

networks:
  sw-network:

volumes:
  postgres-data:
  opensearch-data:
