# Generated by Django 6.0.1 on 2026-01-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Words",
            new_name="Word",
        ),
    ]
