# Generated by Django 6.0.1 on 2026-02-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0002_rename_words_word"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="word",
            name="term",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name="word",
            name="tags",
            field=models.ManyToManyField(blank=True, to="dictionary.tag"),
        ),
    ]
