# Generated by Django 6.0.1 on 2026-02-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0003_tag_alter_word_term_word_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
