# Generated by Django 6.0.1 on 2026-02-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0004_tag_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="term",
            field=models.CharField(max_length=200),
        ),
    ]
