# Generated by Django 6.0.1 on 2026-06-25 08:55

import dictionary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_alter_word_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pronunciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='pronunciations/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'm4a', 'ogg', 'wav', 'webm']), dictionary.models.validate_audio_file_size])),
                ('label', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciations', to='dictionary.word')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
