# --- DEVCONTAINER ---
services:
  workspace:
    build:
      context: .
      dockerfile: docker/workspace/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    networks:
      - sw-network
