name: Build, Push and Deploy to Azure

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push proxy
      run: |
        docker build . -f ./docker/proxy/Dockerfile \
          -t ${{ secrets.ACR_NAME }}.azurecr.io/proxy:${{ github.sha }} \
          -t ${{ secrets.ACR_NAME }}.azurecr.io/proxy:latest
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/proxy:${{ github.sha }}
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/proxy:latest

    - name: Build and push setup
      run: |
        docker build . -f ./docker/setup/Dockerfile \
          -t ${{ secrets.ACR_NAME }}.azurecr.io/setup:${{ github.sha }} \
          -t ${{ secrets.ACR_NAME }}.azurecr.io/setup:latest
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/setup:${{ github.sha }}
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/setup:latest
