name: Build, Push and Deploy to Azure

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file ./docker/proxy/Dockerfile --tag proxy:$(date +%s)
